#This SPARQL query extracts all Protein Objects as NCBI IDs from all KEs
SELECT DISTINCT  ?keid ?ketitle ?objectname ?prot
WHERE {
    ?aop a aopo:AdverseOutcomePathway ;
        aopo:has_key_event ?ke.
    ?ke pato:0001241 ?object; 
        dc:title ?ketitle; 
        rdfs:label ?keid.
    ?object dc:title ?objectname; 
        skos:exactMatch ?prot.
    ?prot a edam:data_1027.
} 
